TitleHunt/TitleHunt/Controllers/TitleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TitleHunt.Models;

namespace TitleHunt.Controllers
{ 
    public class TitleController : Controller
    {
        private TitlesEntities db = new TitlesEntities();

        //
        // GET: /Title/

        public ViewResult Index()
        {
            var title = from t in db.Titles
                        join tg in db.TitleGenres on t.TitleId equals tg.TitleId
                        join g in db.Genres on tg.GenreId equals g.Id
                        join s in db.StoryLines on t.TitleId equals s.TitleId
                        join tp in db.TitleParticipants on t.TitleId equals tp.TitleId
                        join p in db.Participants       on tp.ParticipantId equals p.Id
                        where (tp.RoleType == "Producer") || (tp.RoleType == "Director")
                        select new TitleView
                        {
                            TitleId = t.TitleId,
                            TitleName = t.TitleName,
                            ReleaseYear = t.ReleaseYear,
                            GenreName = g.Name,
                            Description = s.Description.Substring(0, 100),
                            Participant = p.Name,
                            Role = tp.RoleType
                        };

            return View(title.ToList().OrderBy(a => a.TitleName).ThenBy(b => b.TitleId).ThenBy(c => c.Role));
        }

        //
        // GET: /Title/Details/5

        public ViewResult Details(int id)
        {
            
            var title = from t in db.Titles
                        join tg in db.TitleGenres on t.TitleId equals tg.TitleId
                        join g in db.Genres on tg.GenreId equals g.Id
                        join s in db.StoryLines on t.TitleId equals s.TitleId
                        join tp in db.TitleParticipants on t.TitleId equals tp.TitleId
                        join p in db.Participants on tp.ParticipantId equals p.Id
                        join aw in db.Awards on t.TitleId equals aw.TitleId into awt
                        from aw in awt.DefaultIfEmpty()

                        where t.TitleId == id
                        
                        select new TitleView
                        {
                            TitleId = t.TitleId,
                            TitleName = t.TitleName,
                            ReleaseYear = t.ReleaseYear,
                            GenreName = g.Name,
                            Description = s.Description,
                            Participant = p.Name,
                            Role = tp.RoleType,
                            ParticipantType = p.ParticipantType,
                            IsKey = tp.IsKey,
                            IsOnScreen = tp.IsOnScreen,
                            ParticipantId = tp.ParticipantId,
                            Award = aw.Award1,
                            AwardCompany = aw.AwardCompany,
                            AwardWon = aw.AwardWon,
                            AwardYear = aw.AwardYear
                        };

            return View(title.ToList().OrderBy(a => a.TitleName).ThenBy(b => b.TitleId).ThenBy(c => c.ParticipantId).ThenBy(d => d.AwardWon).ThenBy(e => e.Award).ThenBy(f => f.AwardCompany));

        }

        //public ViewResult Details(int id)
        //{
        //    var title = from t in db.Titles
        //                join tg in db.TitleGenres on t.TitleId equals tg.TitleId
        //                join g in db.Genres on tg.GenreId equals g.Id
        //                join s in db.StoryLines on t.TitleId equals s.TitleId
        //                join tp in db.TitleParticipants on t.TitleId equals tp.TitleId
        //                join p in db.Participants on tp.ParticipantId equals p.Id
        //                join aw in db.Awards on t.TitleId equals aw.TitleId into awt
        //                from aw in awt.DefaultIfEmpty()

        //                where t.TitleId == id

        //                select new TitleView
        //                {
        //                    TitleId = t.TitleId,
        //                    TitleName = t.TitleName,
        //                    ReleaseYear = t.ReleaseYear,
        //                    GenreName = g.Name,
        //                    Description = s.Description,
        //                    Participant = p.Name,
        //                    Role = tp.RoleType,
        //                    ParticipantType = p.ParticipantType,
        //                    IsKey = tp.IsKey,
        //                    IsOnScreen = tp.IsOnScreen,
        //                    ParticipantId = tp.ParticipantId,
        //                    Award = aw.Award1,
        //                    AwardCompany = aw.AwardCompany,
        //                    AwardWon = aw.AwardWon,
        //                    AwardYear = aw.AwardYear
        //                };

        //    var awards = from t in db.Titles
        //                 join aw in db.Awards on t.TitleId equals aw.TitleId into awt
        //                 from aw in awt.DefaultIfEmpty()

        //                 where t.TitleId == id

        //                 select new AwardsModel
        //                 {
        //                     TitleId = t.TitleId,
        //                     TitleName = t.TitleName,
        //                     ReleaseYear = t.ReleaseYear,

        //                     Award = aw.Award1,
        //                     AwardCompany = aw.AwardCompany,
        //                     AwardWon = aw.AwardWon,
        //                     AwardYear = aw.AwardYear
        //                 };
        //    var mainModel = new MainModel() { TitleList = title.ToList(), AwardList= awards.ToList() };

        //    return View(mainModel);

        //}

        //public void CreateAwardsView(int id) 
        //{
        //    var awards = from t in db.Titles
        //                join aw in db.Awards on t.TitleId equals aw.TitleId into awt
        //                from aw in awt.DefaultIfEmpty()

        //                where t.TitleId == id

        //                select new AwardsModel
        //                {
        //                    TitleId = t.TitleId,
        //                    TitleName = t.TitleName,
        //                    ReleaseYear = t.ReleaseYear,
                            
        //                    Award = aw.Award1,
        //                    AwardCompany = aw.AwardCompany,
        //                    AwardWon = aw.AwardWon,
        //                    AwardYear = aw.AwardYear
        //                };        
        //}

        //
        // GET: /Title/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Title/Create

        [HttpPost]
        public ActionResult Create(Title title)
        {
            if (ModelState.IsValid)
            {
                db.Titles.AddObject(title);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(title);
        }
        
        //
        // GET: /Title/Edit/5
 
        public ActionResult Edit(int id)
        {
            Title title = db.Titles.Single(t => t.TitleId == id);
            return View(title);
        }

        //
        // POST: /Title/Edit/5

        [HttpPost]
        public ActionResult Edit(Title title)
        {
            if (ModelState.IsValid)
            {
                db.Titles.Attach(title);
                db.ObjectStateManager.ChangeObjectState(title, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(title);
        }

        //
        // GET: /Title/Delete/5
 
        public ActionResult Delete(int id)
        {
            Title title = db.Titles.Single(t => t.TitleId == id);
            return View(title);
        }

        //
        // POST: /Title/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Title title = db.Titles.Single(t => t.TitleId == id);
            db.Titles.DeleteObject(title);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult Browse(string genre) 
        {

            var title = from t in db.Titles
                        join tg in db.TitleGenres on t.TitleId equals tg.TitleId
                        join g in db.Genres on tg.GenreId equals g.Id
                        join s in db.StoryLines on t.TitleId equals s.TitleId
                        join tp in db.TitleParticipants on t.TitleId equals tp.TitleId
                        join p in db.Participants on tp.ParticipantId equals p.Id
                        where ((tp.RoleType == "Producer") || (tp.RoleType == "Director"))
                        && (g.Name == genre)
                        select new TitleView
                        {
                            TitleId = t.TitleId,
                            TitleName = t.TitleName,
                            ReleaseYear = t.ReleaseYear,
                            GenreName = g.Name,
                            Description = s.Description.Substring(0, 100),
                            Participant = p.Name,
                            Role = tp.RoleType
                        };

            return View(title.ToList().OrderBy(a => a.TitleName).ThenBy(b => b.TitleId).ThenBy(c => c.Role));

        }

        public ActionResult AlphaBrowse(string alpha)
        {
        var title = from t in db.Titles

TitleHunt/TitleHunt/Views/Shared/_Awards.cshtml
@model IEnumerable<TitleHunt.Models.TitleView>

@{
    ViewBag.Title = "Details";
    bool bDisplayRec = true;
    bool bDisplayNom = true;
    
    string award = "";
    string awardString = "";
    string nomString = "";
}
@foreach (var item in Model)
{
    if (item.Award != null)
    {
        
        award = item.Award;
        
        if (item.AwardWon == true)
        {
            bool bAwardExists = award.All(a => awardString.Contains(a));
            if (!(bAwardExists))
            {
                if (bDisplayRec)
                { 
                    
                    <h3>Awards won:</h3>
                    bDisplayRec = false;
                }
                awardString = awardString + "," + award;
            
                @item.Award;<br />
                        
            
            }
        }
        
        if (item.AwardWon == false)
        {
        
            bool bAwardNominated = award.All(a => nomString.Contains(a));
            if (!(bAwardNominated))
            {
                if (bDisplayNom)
                { 
                    <h3>Nominations:</h3>
                    
                    bDisplayNom = false;
                }
                nomString = nomString + "," + award;
                    @item.Award;<br />
            }
        
        
        }
        
    }


}

TitleHunt/TitleHunt/Views/Shared/_GenreMenu.cshtml
@using (Html.BeginForm("SearchDB", "Title", FormMethod.Post))
    {
    
    <table border="0" cellpadding="10" width="55%" cellspacing="0">
        <tr>
            <td>
                Search Title:
            </td>
            <td colspan="6" valign=middle>
                @Html.TextBox("Search")

                <input type=submit value="Search" />
                
            </td>
        </tr>
        <tr>
            <td>
                Most popular Genres:
            </td>
            <td>
                @Html.ActionLink("Action", "Browse", new { Genre = "Action" })
            </td>
            <td>
                @Html.ActionLink("Comedy", "Browse", new { Genre = "Comedy" })
            </td>
            <td>
                @Html.ActionLink("Drama", "Browse", new { Genre = "Drama" })
            </td>
            <td>
                @Html.ActionLink("Family", "Browse", new { Genre = "Family" })
            </td>
            <td>
                @Html.ActionLink("More...", "ComingSoon")
            </td>
        </tr>
        <tr>
            <td colspan=10>
                @Html.ActionLink("A", "AlphaBrowse", new { Alpha = "A" })&nbsp;&nbsp;
                @Html.ActionLink("B", "AlphaBrowse", new { Alpha = "B" })&nbsp;&nbsp;
                @Html.ActionLink("C", "AlphaBrowse", new { Alpha = "C" })&nbsp;&nbsp;
                @Html.ActionLink("D", "AlphaBrowse", new { Alpha = "D" })&nbsp;&nbsp;
                @Html.ActionLink("E", "AlphaBrowse", new { Alpha = "E" })&nbsp;&nbsp;
                @Html.ActionLink("F", "AlphaBrowse", new { Alpha = "F" })&nbsp;&nbsp;
                @Html.ActionLink("G", "AlphaBrowse", new { Alpha = "G" })&nbsp;&nbsp;
                @Html.ActionLink("H", "AlphaBrowse", new { Alpha = "H" })&nbsp;&nbsp;
                @Html.ActionLink("I", "AlphaBrowse", new { Alpha = "I" })&nbsp;&nbsp;
                @Html.ActionLink("J", "AlphaBrowse", new { Alpha = "J" })&nbsp;&nbsp;
                @Html.ActionLink("K", "AlphaBrowse", new { Alpha = "K" })&nbsp;&nbsp;
                @Html.ActionLink("L", "AlphaBrowse", new { Alpha = "L" })&nbsp;&nbsp;
                @Html.ActionLink("M", "AlphaBrowse", new { Alpha = "M" })&nbsp;&nbsp;
                @Html.ActionLink("N", "AlphaBrowse", new { Alpha = "N" })&nbsp;&nbsp;
                @Html.ActionLink("O", "AlphaBrowse", new { Alpha = "O" })&nbsp;&nbsp;
                @Html.ActionLink("P", "AlphaBrowse", new { Alpha = "P" })&nbsp;&nbsp;
                @Html.ActionLink("Q", "AlphaBrowse", new { Alpha = "Q" })&nbsp;&nbsp;
                @Html.ActionLink("R", "AlphaBrowse", new { Alpha = "R" })&nbsp;&nbsp;
                @Html.ActionLink("S", "AlphaBrowse", new { Alpha = "S" })&nbsp;&nbsp;
                @Html.ActionLink("T", "AlphaBrowse", new { Alpha = "T" })&nbsp;&nbsp;
                @Html.ActionLink("U", "AlphaBrowse", new { Alpha = "U" })&nbsp;&nbsp;
                @Html.ActionLink("V", "AlphaBrowse", new { Alpha = "V" })&nbsp;&nbsp;
                @Html.ActionLink("W", "AlphaBrowse", new { Alpha = "W" })&nbsp;&nbsp;
                @Html.ActionLink("X", "AlphaBrowse", new { Alpha = "X" })&nbsp;&nbsp;
                @Html.ActionLink("Y", "AlphaBrowse", new { Alpha = "Y" })&nbsp;&nbsp;
                @Html.ActionLink("Z", "AlphaBrowse", new { Alpha = "Z" })&nbsp;&nbsp;
                
            </td>
        </tr>
    </table>
}

TitleHunt/TitleHunt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="menucontainer">
                <ul id="menu">
                    <li class="selected">@Html.ActionLink("Title", "Index", "Title")</li>
                    <li>@Html.ActionLink("Genre", "ComingSoon", "Title")</li>
                    <li>@Html.ActionLink("Actors", "ComingSoon", "Title")</li>
                    <li>@Html.ActionLink("Showtimes", "ComingSoon", "Title")</li>
                    <li>@Html.ActionLink("Trailers", "ComingSoon", "Title")</li>
                    <li>@Html.ActionLink("TV", "ComingSoon", "Title")</li>
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>

TitleHunt/TitleHunt/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

TitleHunt/TitleHunt/Views/Shared/_MovieCast.cshtml
@model IEnumerable<TitleHunt.Models.TitleView>
@{
    ViewBag.Title = "Details";
    string particpantType = "";
    string roleType = "";
    string personName = "";
    bool? isKey = false;
    bool? isOnScreen = false;
    string dirString = "";
    string prevDir = "";
    string prodString = "";
    string prevProd = "";
    string keyString = "";
    string prevKey = "";
    string prevCast = "";
    string castString = "";
        
}
@foreach (var item in Model)
{
    roleType = item.Role;
    personName = item.Participant;
    isKey = item.IsKey;
    isOnScreen = item.IsOnScreen;
    particpantType = item.ParticipantType;



    if (roleType == "Director")
    {
        bool bDirExists = personName.All(a => dirString.Contains(a));
        if (!(bDirExists))
        {
            dirString = dirString + ", " + personName;
        }
        prevDir = personName;
    }
    else if (roleType == "Producer")
    {
        bool bProdExists = personName.All(a => prodString.Contains(a));
        if (!(bProdExists))
        {
            prodString = prodString + ", " + personName;
        }
        prevProd = personName;
    }

    if ((isOnScreen == true) && (particpantType == "Person") && (roleType == "Actor"))
    {
        if (isKey == true)
        {
            bool bKeyExists = personName.All(a => keyString.Contains(a));
            if (!(bKeyExists))
            {
                keyString = keyString + ", " + personName;
            }        
        }
        else 
        {
            bool bCastExists = personName.All(c => castString.Contains(c));
            if (!(bCastExists))
            {
                castString = castString + ", " + personName;
            }
            prevCast = personName;
        
        }
        prevKey = personName;
        
    }
}
@{
    if (dirString.Length > 0)
    {
        dirString = dirString.Substring(1, dirString.Length - 1);
    }
    if (prodString.Length > 0)
    {
        prodString = prodString.Substring(1, prodString.Length - 1);
    }
    if (keyString.Length > 0)
    {
        keyString = keyString.Substring(1, keyString.Length - 1);
    }
    if (castString.Length > 0)
    {
        castString = castString.Substring(1, castString.Length - 1);
    }   
}
@dirString
<h3>Producer(s):</h3>
@prodString
<h3>Lead Cast:</h3>
@keyString
<h3>Also starring:</h3>
@castString

TitleHunt/TitleHunt/Views/Shared/_StoryLine.cshtml
@model IEnumerable<TitleHunt.Models.TitleView>

@{
    ViewBag.Title = "Details";
    bool bDisplayRec = true;
}
@foreach (var item in Model)
{
    if (bDisplayRec)
    {
    <table width="100%" cellpadding="50">
        <tr>
            <td>                
                @Html.DisplayFor(model => item.Description)                
            </td>
        </tr>
    </table>
        bDisplayRec = false;
    }
}

TitleHunt/TitleHunt/Views/Shared/login.cshtml
@model IEnumerable<TitleHunt.Models.TitleView>
@{
    ViewBag.Title = "Details";
    bool bDisplayRec = true;
}
@foreach (var item in Model)
{
    if (bDisplayRec)
    {
    <table width="100%" cellpadding="0">
        <tr>
            <td width="35%" valign="top">
            <h1>@Html.DisplayFor(model => item.TitleName)&nbsp;(@Html.DisplayFor(model => item.ReleaseYear))</h1><br />
                <img src="../../Content/images/coming_soon.jpg" /><br />
                
            </td>
        </tr>
    </table>
        bDisplayRec = false;
    }
}